"""Execute saved Listing image export plans for the content factory."""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from typing import Any

from fastapi import HTTPException
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.content_asset import ContentAsset
from app.services.content_asset_service import (
    asset_path,
    create_image_asset_from_bytes,
    edit_image_from_url,
    get_asset,
)
from app.services.content_workbench_service import (
    _get_content_item,
    _stored_tasks,
    confirm_content_task_version,
    save_content_task_version,
)

LOCAL_ASSET_FILE_RE = re.compile(r"/api/v1/content/assets/([^/]+)/file$")


async def execute_image_export_tasks(
    db: AsyncSession,
    user_id: str,
    item_id: str,
    *,
    task_ids: list[str] | None = None,
    limit: int = 30,
) -> dict[str, Any]:
    """Turn planned image export tasks into persisted content assets.

    The service consumes the confirmed ``image_edit_plan`` JSON generated by the
    Listing image workbench. It only creates local ``ContentAsset`` records and
    writes a new confirmed task version with execution statuses; platform upload
    remains the responsibility of the batch listing module.
    """

    item = await _get_content_item(db, user_id, item_id)
    payload, version = _confirmed_image_plan_payload(item)
    export_tasks = _export_tasks(payload)
    selected_task_ids = {task_id for task_id in (task_ids or []) if task_id}
    pending = [
        task for task in export_tasks
        if task.get("status") != "exported_to_content_asset"
        and (not selected_task_ids or str(task.get("task_id") or "") in selected_task_ids)
    ][:max(1, min(limit, 30))]
    if not pending:
        return {
            "executed": 0,
            "failed": 0,
            "skipped": len(export_tasks),
            "assets": [],
            "task_version": version,
            "message": "没有待执行的图片导出任务",
        }

    slots_by_position = _slots_by_position(payload)
    created_assets: list[ContentAsset] = []
    failed: list[dict[str, Any]] = []
    executed_at = datetime.now(timezone.utc).isoformat()
    for task in pending:
        try:
            position = int(task.get("position") or 0)
            slot = slots_by_position.get(position, {})
            options = _image_options(task, slot)
            source_url = str(task.get("source_image_url") or slot.get("image_url") or "").strip()
            if not source_url:
                raise HTTPException(status_code=400, detail="图片导出任务缺少源图")
            asset = await _create_asset_from_source(
                db,
                user_id,
                source_url,
                options,
                content_item_id=item_id,
                original_name=str(task.get("asset_name") or slot.get("asset_name") or f"slot-{position}"),
                position=position,
            )
            created_assets.append(asset)
            task.update({
                "status": "exported_to_content_asset",
                "generated_asset_id": asset.id,
                "generated_asset_url": f"/api/v1/content/assets/{asset.id}/file",
                "generated_width": asset.width,
                "generated_height": asset.height,
                "executed_at": executed_at,
                "error": None,
            })
            if slot:
                slot["image_url"] = f"/api/v1/content/assets/{asset.id}/file"
                slot["asset_name"] = asset.original_name or asset.id
                slot["size"] = f"{asset.width}×{asset.height}px"
        except Exception as exc:  # noqa: BLE001 - must write per-task status instead of aborting all tasks
            task.update({
                "status": "export_failed",
                "error": _error_message(exc),
                "executed_at": executed_at,
            })
            failed.append({"task_id": task.get("task_id"), "error": _error_message(exc)})

    payload["export_tasks"] = export_tasks
    payload["last_export_execution"] = {
        "executed_at": executed_at,
        "executed": len(created_assets),
        "failed": len(failed),
        "boundary": "content_workbench_image_export_execution",
    }
    _recount_image_plan(payload)
    saved = await save_content_task_version(
        db,
        user_id,
        item_id,
        "image_edit_plan",
        json.dumps(payload, ensure_ascii=False, indent=2),
        provider="system_image_export_tasks",
    )
    await confirm_content_task_version(db, user_id, item_id, "image_edit_plan", saved["version"])
    return {
        "executed": len(created_assets),
        "failed": len(failed),
        "skipped": max(0, len(export_tasks) - len(pending)),
        "assets": [_asset_result(asset) for asset in created_assets],
        "failures": failed,
        "task_version": saved,
        "message": "图片导出任务已执行并回写当前 Listing 图片计划",
    }


def _confirmed_image_plan_payload(item: Any) -> tuple[dict[str, Any], int | None]:
    tasks = _stored_tasks(item)
    record = tasks.get("image_edit_plan") or {}
    confirmed_version = record.get("confirmed_version")
    version = next((item for item in record.get("versions") or [] if item.get("version") == confirmed_version), None)
    if not version:
        raise HTTPException(status_code=409, detail="当前商品没有已确认的图片槽位计划")
    try:
        payload = json.loads(version.get("content") or "{}")
    except json.JSONDecodeError as exc:
        raise HTTPException(status_code=409, detail="已确认图片计划不是有效 JSON") from exc
    if payload.get("schema") != "listing_image_slots.v1":
        raise HTTPException(status_code=409, detail="已确认图片计划不是 listing_image_slots.v1")
    return payload, confirmed_version


def _export_tasks(payload: dict[str, Any]) -> list[dict[str, Any]]:
    tasks = payload.get("export_tasks") or []
    if not isinstance(tasks, list):
        raise HTTPException(status_code=409, detail="图片导出任务结构无效")
    if not tasks:
        raise HTTPException(status_code=409, detail="图片计划中没有可执行导出任务")
    return [task for task in tasks if isinstance(task, dict)]


def _slots_by_position(payload: dict[str, Any]) -> dict[int, dict[str, Any]]:
    slots = payload.get("slots") or []
    if not isinstance(slots, list):
        return {}
    rows: dict[int, dict[str, Any]] = {}
    for slot in slots:
        if not isinstance(slot, dict):
            continue
        try:
            rows[int(slot.get("position") or 0)] = slot
        except (TypeError, ValueError):
            continue
    return rows


def _image_options(task: dict[str, Any], slot: dict[str, Any]) -> dict[str, Any]:
    options = dict(slot.get("edit_options") or {})
    if task.get("target_width"):
        options["width"] = task["target_width"]
    if task.get("target_height"):
        options["height"] = task["target_height"]
    for key in ("fit", "crop_mode", "output_format", "quality"):
        if task.get(key) is not None:
            options[key] = task[key]
    return options


async def _create_asset_from_source(
    db: AsyncSession,
    user_id: str,
    source_url: str,
    options: dict[str, Any],
    *,
    content_item_id: str,
    original_name: str,
    position: int,
) -> ContentAsset:
    local_asset_id = _local_asset_id(source_url)
    if local_asset_id:
        source_asset = await get_asset(db, user_id, local_asset_id)
        content = asset_path(source_asset).read_bytes()
        return await create_image_asset_from_bytes(
            db,
            user_id,
            content,
            options,
            original_name=original_name or source_asset.original_name,
            operation="listing_image_export",
            extra={
                "content_item_id": content_item_id,
                "source_asset_id": source_asset.id,
                "slot_position": position,
                "boundary": "content_workbench_image_export_execution",
            },
        )
    return await edit_image_from_url(db, user_id, source_url, {
        **options,
        "content_item_id": content_item_id,
        "slot_position": position,
        "boundary": "content_workbench_image_export_execution",
    }, content_item_id=content_item_id)


def _local_asset_id(source_url: str) -> str | None:
    match = LOCAL_ASSET_FILE_RE.search(source_url)
    return match.group(1) if match else None


def _recount_image_plan(payload: dict[str, Any]) -> None:
    slots = [slot for slot in payload.get("slots") or [] if isinstance(slot, dict)]
    payload["publishable_image_count"] = sum(1 for slot in slots if slot.get("image_url") and slot.get("publishable") is not False)
    payload["retained_image_count"] = sum(1 for slot in slots if slot.get("image_url") and slot.get("publishable") is False)


def _asset_result(asset: ContentAsset) -> dict[str, Any]:
    return {
        "id": asset.id,
        "url": f"/api/v1/content/assets/{asset.id}/file",
        "width": asset.width,
        "height": asset.height,
        "operation": asset.operation,
        "original_name": asset.original_name,
    }


def _error_message(exc: Exception) -> str:
    if isinstance(exc, HTTPException):
        return str(exc.detail)
    return str(exc)
