import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FRONTEND_SRC = ROOT / "frontend/src"
INDEX_CSS = (ROOT / "frontend/src/index.css").read_text(encoding="utf-8")
STYLE_MODULES_CSS = (ROOT / "frontend/src/styles/modules.css").read_text(encoding="utf-8")
ALL_STYLE_CSS = INDEX_CSS + "\n" + "\n".join(
    sorted(path.read_text(encoding="utf-8") for path in (ROOT / "frontend/src/styles").glob("*.css"))
)
COCKPIT_CSS = (ROOT / "frontend/src/styles/cockpit.css").read_text(encoding="utf-8")
RISK_CONTROL_CSS = (ROOT / "frontend/src/styles/risk-control.css").read_text(encoding="utf-8")
BUSINESS_FLOW_CSS = (ROOT / "frontend/src/styles/business-flow.css").read_text(encoding="utf-8")
CONTENT_FACTORY_CSS = (ROOT / "frontend/src/styles/content-factory.css").read_text(encoding="utf-8")
LISTING_EDITOR_CSS = (ROOT / "frontend/src/styles/listing-editor.css").read_text(encoding="utf-8")
LISTING_SPEC_EDITOR_CSS = (ROOT / "frontend/src/styles/listing-spec-editor.css").read_text(encoding="utf-8")
PRODUCT_INVENTORY_CSS = (ROOT / "frontend/src/styles/product-inventory.css").read_text(encoding="utf-8")
BATCH_PUBLISH_CSS = (ROOT / "frontend/src/styles/batch-publish.css").read_text(encoding="utf-8")
PRICING_CSS = (ROOT / "frontend/src/styles/pricing.css").read_text(encoding="utf-8")
REPORTS_CSS = (ROOT / "frontend/src/styles/reports.css").read_text(encoding="utf-8")
ORDERS_CSS = (ROOT / "frontend/src/styles/orders.css").read_text(encoding="utf-8")
FINANCE_CSS = (ROOT / "frontend/src/styles/finance.css").read_text(encoding="utf-8")
SETTINGS_CSS = (ROOT / "frontend/src/styles/settings.css").read_text(encoding="utf-8")
GROWTH_CSS = (ROOT / "frontend/src/styles/growth.css").read_text(encoding="utf-8")
COMPETITOR_CSS = (ROOT / "frontend/src/styles/competitor.css").read_text(encoding="utf-8")
OPERATIONS_CSS = (ROOT / "frontend/src/styles/operations.css").read_text(encoding="utf-8")
PROMOTIONS_CSS = (ROOT / "frontend/src/styles/promotions.css").read_text(encoding="utf-8")
INVENTORY_ALERTS_CSS = (ROOT / "frontend/src/styles/inventory-alerts.css").read_text(encoding="utf-8")
AI_SUGGESTIONS_CSS = (ROOT / "frontend/src/styles/ai-suggestions.css").read_text(encoding="utf-8")
LISTING_TEMPLATES_CSS = (ROOT / "frontend/src/styles/listing-templates.css").read_text(encoding="utf-8")
LUXURY_SYSTEM_CSS = (ROOT / "frontend/src/styles/luxury-system.css").read_text(encoding="utf-8")
MATERIO_SYSTEM_CSS = (
    (ROOT / "frontend/src/styles/materio-system.css").read_text(encoding="utf-8")
    + "\n"
    + "\n".join(
        path.read_text(encoding="utf-8")
        for path in sorted((ROOT / "frontend/src/styles").glob("materio-*.css"))
        if path.name != "materio-system.css"
    )
)
NATIVE_CONFIRM_ALLOWLIST = {
    "frontend/src/components/ui/ConfirmDialog.tsx",
}
MODULE_SUBNAV = (ROOT / "frontend/src/components/layout/ModuleSubnav.tsx").read_text(encoding="utf-8")
TABS_COMPONENT = (ROOT / "frontend/src/components/ui/Tabs.tsx").read_text(encoding="utf-8")
BADGE_COMPONENT = (ROOT / "frontend/src/components/ui/Badge.tsx").read_text(encoding="utf-8")
DATA_TABLE = (ROOT / "frontend/src/components/shared/DataTable.tsx").read_text(encoding="utf-8")
SIDEBAR = (ROOT / "frontend/src/components/layout/Sidebar.tsx").read_text(encoding="utf-8")
FILTER_BAR = (ROOT / "frontend/src/components/shared/FilterBar.tsx").read_text(encoding="utf-8")
NAVIGATION = (ROOT / "frontend/src/components/layout/navigation.ts").read_text(encoding="utf-8")
ROUTE_META = (ROOT / "frontend/src/components/layout/routeMeta.ts").read_text(encoding="utf-8")
SETTINGS_WORKSPACE = (ROOT / "frontend/src/features/settings/SettingsWorkspace.tsx").read_text(encoding="utf-8")
SETTINGS_ACCOUNT_PANELS = (ROOT / "frontend/src/features/settings/SettingsAccountPanels.tsx").read_text(encoding="utf-8")
SETTINGS_DATA_PANELS_MAIN = (ROOT / "frontend/src/features/settings/SettingsDataPanels.tsx").read_text(encoding="utf-8")
SETTINGS_DATA_PANELS_PARTS = (ROOT / "frontend/src/features/settings/SettingsDataPanelsParts.tsx").read_text(encoding="utf-8")
SETTINGS_DATA_PANELS = "\n".join([SETTINGS_DATA_PANELS_MAIN, SETTINGS_DATA_PANELS_PARTS])
PLATFORM_FIELD_GROUP_GOVERNANCE = (ROOT / "frontend/src/features/settings/PlatformFieldGroupGovernance.tsx").read_text(encoding="utf-8")
SETTINGS_SYSTEM_PANELS = (ROOT / "frontend/src/features/settings/SettingsSystemPanels.tsx").read_text(encoding="utf-8")
SETTINGS_TASKS_PAGE = (ROOT / "frontend/src/pages/SettingsTasksPage.tsx").read_text(encoding="utf-8")
SETTINGS_ACCESS_PANEL = (ROOT / "frontend/src/features/settings/SettingsAccessPanel.tsx").read_text(encoding="utf-8")
SEED_MANAGER_TAB = (ROOT / "frontend/src/features/settings/SeedManagerTab.tsx").read_text(encoding="utf-8")
HEADER = (ROOT / "frontend/src/components/layout/Header.tsx").read_text(encoding="utf-8")
NOTIFICATION_BELL = (ROOT / "frontend/src/components/layout/NotificationBell.tsx").read_text(encoding="utf-8")
APP_LAYOUT = (ROOT / "frontend/src/components/layout/AppLayout.tsx").read_text(encoding="utf-8")
APP = (ROOT / "frontend/src/App.tsx").read_text(encoding="utf-8")
DESIGN_SYSTEM_PAGE = (ROOT / "frontend/src/pages/DesignSystemPage.tsx").read_text(encoding="utf-8")
THEME_CONTEXT = (ROOT / "frontend/src/contexts/ThemeContext.tsx").read_text(encoding="utf-8")
CARD_COMPONENT = (ROOT / "frontend/src/components/ui/Card.tsx").read_text(encoding="utf-8")
BUTTON_COMPONENT = (ROOT / "frontend/src/components/ui/Button.tsx").read_text(encoding="utf-8")
INPUT_COMPONENT = (ROOT / "frontend/src/components/ui/Input.tsx").read_text(encoding="utf-8")
MODAL_COMPONENT = (ROOT / "frontend/src/components/ui/Modal.tsx").read_text(encoding="utf-8")
EMPTY_STATE_COMPONENT = (ROOT / "frontend/src/components/ui/EmptyState.tsx").read_text(encoding="utf-8")
SELECT_COMPONENT = (ROOT / "frontend/src/components/ui/Select.tsx").read_text(encoding="utf-8")
CHECKBOX_COMPONENT = (ROOT / "frontend/src/components/ui/Checkbox.tsx").read_text(encoding="utf-8")
RADIO_GROUP_COMPONENT = (ROOT / "frontend/src/components/ui/RadioGroup.tsx").read_text(encoding="utf-8")
SWITCH_COMPONENT = (ROOT / "frontend/src/components/ui/Switch.tsx").read_text(encoding="utf-8")
PAGE_HEADER_COMPONENT = (ROOT / "frontend/src/components/shared/PageHeader.tsx").read_text(encoding="utf-8")
OPERATIONS_WORKSPACE = (ROOT / "frontend/src/features/operations/OperationsWorkspace.tsx").read_text(encoding="utf-8")
SCOUT_WORKSPACE = (ROOT / "frontend/src/features/scout-sources/ScoutSourcesWorkspace.tsx").read_text(encoding="utf-8")
SCOUT_SOURCES_VIEW = (ROOT / "frontend/src/features/scout-sources/ScoutSourcesView.tsx").read_text(encoding="utf-8")
SIGNAL_FUNNEL_OVERVIEW = (ROOT / "frontend/src/features/scout-sources/SignalFunnelOverview.tsx").read_text(encoding="utf-8")
SCOUT_STAGE_RAIL = (ROOT / "frontend/src/features/scout-sources/ScoutStageRail.tsx").read_text(encoding="utf-8")
CONTENT_STAGE_RAIL_PATH = ROOT / "frontend/src/features/content-planner/ContentListingStageRail.tsx"
CONTENT_STAGE_RAIL = CONTENT_STAGE_RAIL_PATH.read_text(encoding="utf-8") if CONTENT_STAGE_RAIL_PATH.exists() else ""
SELECTION_PIPELINE = (ROOT / "frontend/src/components/shared/SelectionBusinessPipeline.tsx").read_text(encoding="utf-8")
BUSINESS_FLOW_V2 = (ROOT / "frontend/src/features/business-flow/BusinessFlowV2Board.tsx").read_text(encoding="utf-8")
BUSINESS_FLOW_WORKSPACE = (ROOT / "frontend/src/features/business-flow/BusinessFlowWorkspace.tsx").read_text(encoding="utf-8")
BUSINESS_FLOW_COMMAND_BOARD = (ROOT / "frontend/src/features/business-flow/BusinessFlowCommandBoard.tsx").read_text(encoding="utf-8")
BUSINESS_FLOW_COMMAND_BOARD_PARTS = (ROOT / "frontend/src/features/business-flow/BusinessFlowCommandBoardParts.tsx").read_text(encoding="utf-8")
BUSINESS_FLOW_COMMAND_BOARD_SURFACE = "\n".join([BUSINESS_FLOW_COMMAND_BOARD, BUSINESS_FLOW_COMMAND_BOARD_PARTS])
BUSINESS_FLOW_CONTEXT_RAIL = (ROOT / "frontend/src/features/business-flow/BusinessFlowContextRail.tsx").read_text(encoding="utf-8")
BUSINESS_FLOW_ROUTES = (ROOT / "frontend/src/features/business-flow/businessFlowRoutes.ts").read_text(encoding="utf-8")
COMPARISON_RANGE_UTIL = (ROOT / "frontend/src/utils/comparisonRange.ts").read_text(encoding="utf-8")
COMPARISON_RANGE_CARDS = (ROOT / "frontend/src/components/shared/ComparisonRangeCards.tsx").read_text(encoding="utf-8")
COMMAND_INSIGHT_STRIP = (ROOT / "frontend/src/components/shared/CommandInsightStrip.tsx").read_text(encoding="utf-8")
METRIC_STACK_BAR = (ROOT / "frontend/src/components/shared/MetricStackBar.tsx").read_text(encoding="utf-8")
STORE_CONTEXT_BANNER = (ROOT / "frontend/src/components/shared/StoreContextBanner.tsx").read_text(encoding="utf-8")
RISK_CONTROL_WORKSPACE_MAIN = (ROOT / "frontend/src/features/risk-control/RiskControlWorkspace.tsx").read_text(encoding="utf-8")
RISK_CONTROL_WORKSPACE_PARTS = (ROOT / "frontend/src/features/risk-control/RiskControlWorkspaceParts.tsx").read_text(encoding="utf-8")
RISK_CONTROL_WORKSPACE = "\n".join([RISK_CONTROL_WORKSPACE_MAIN, RISK_CONTROL_WORKSPACE_PARTS])
RISK_SIGNAL_BOARD = (ROOT / "frontend/src/features/risk-control/RiskSignalBoard.tsx").read_text(encoding="utf-8")
RISK_STORE_COMMAND_BOARD = (ROOT / "frontend/src/features/risk-control/RiskStoreCommandBoard.tsx").read_text(encoding="utf-8")
RISK_EVIDENCE_PANEL = (ROOT / "frontend/src/features/risk-control/RiskEvidencePanel.tsx").read_text(encoding="utf-8")
RISK_ACTION_PANEL = (ROOT / "frontend/src/features/risk-control/RiskActionPanel.tsx").read_text(encoding="utf-8")
RISK_CONTROL_API = (ROOT / "frontend/src/api/riskControl.ts").read_text(encoding="utf-8")
COCKPIT_WORKSPACE = (ROOT / "frontend/src/features/cockpit/CockpitWorkspace.tsx").read_text(encoding="utf-8")
COCKPIT_CENTER_SUMMARY = (ROOT / "frontend/src/features/cockpit/CockpitCenterSummaryPanels.tsx").read_text(encoding="utf-8")
COCKPIT_STORE_COMMAND_BOARD = (ROOT / "frontend/src/features/cockpit/CockpitStoreCommandBoard.tsx").read_text(encoding="utf-8")
COCKPIT_SCOPE_FILTERS = (ROOT / "frontend/src/features/cockpit/CockpitScopeFilters.tsx").read_text(encoding="utf-8")
COCKPIT_SIDEBAR = (ROOT / "frontend/src/features/cockpit/CockpitSidebar.tsx").read_text(encoding="utf-8")
COCKPIT_TYPES = (ROOT / "frontend/src/types/cockpit.ts").read_text(encoding="utf-8")
COCKPIT_COMMAND_WIDGETS = (ROOT / "frontend/src/features/cockpit/CockpitCommandWidgets.tsx").read_text(encoding="utf-8")
COCKPIT_METRIC_STRIP = (ROOT / "frontend/src/features/cockpit/CockpitMetricStrip.tsx").read_text(encoding="utf-8")
TREND_DISCOVERY_WORKSPACE = (ROOT / "frontend/src/features/trend-discovery/TrendDiscoveryWorkspace.tsx").read_text(encoding="utf-8")
RECOMMENDATION_EVIDENCE_PANEL = (ROOT / "frontend/src/features/trend-discovery/RecommendationEvidencePanel.tsx").read_text(encoding="utf-8")
RECOMMENDER_READINESS_PANEL = (ROOT / "frontend/src/features/trend-discovery/RecommenderReadinessPanel.tsx").read_text(encoding="utf-8")
TREND_PIPELINE_UTILS = (ROOT / "frontend/src/features/trend-discovery/TrendPipelineUtils.ts").read_text(encoding="utf-8")
TREND_DISCOVERY_FILES = "\n".join(
    path.read_text(encoding="utf-8")
    for path in (ROOT / "frontend/src/features/trend-discovery").glob("*.tsx")
)
PRODUCT_SELECTION_WORKSPACE = (ROOT / "frontend/src/features/product-selection/ProductSelectionWorkspace.tsx").read_text(encoding="utf-8")
PRODUCT_SELECTION_CORE_TABS = (ROOT / "frontend/src/features/product-selection/ProductSelectionCoreTabs.tsx").read_text(encoding="utf-8")
DECISION_CANDIDATE_CONTEXT = (ROOT / "frontend/src/features/product-selection/DecisionCandidateContext.tsx").read_text(encoding="utf-8")
PRICING_ITEM_SELECTOR = (ROOT / "frontend/src/features/pricing/PricingItemSelector.tsx").read_text(encoding="utf-8")
PRICING_TEMPLATE_STORE_PREVIEW = (ROOT / "frontend/src/features/pricing/PricingTemplateStorePreview.tsx").read_text(encoding="utf-8")
PRICING_FEE_TEMPLATE_PANEL = (ROOT / "frontend/src/features/pricing/PricingFeeTemplatePanel.tsx").read_text(encoding="utf-8")
PRICING_DECISION_CONTEXT = (ROOT / "frontend/src/features/pricing/PricingDecisionContext.tsx").read_text(encoding="utf-8")
PRICING_PAGE_UTILS = (ROOT / "frontend/src/features/pricing/PricingPageUtils.ts").read_text(encoding="utf-8")
SMART_PRICING_PAGE = (ROOT / "frontend/src/pages/SmartPricingPage.tsx").read_text(encoding="utf-8")
SMART_PRICING_PAGE_PARTS = (ROOT / "frontend/src/features/pricing/SmartPricingPageParts.tsx").read_text(encoding="utf-8")
SMART_PRICING_SURFACE = "\n".join([SMART_PRICING_PAGE, SMART_PRICING_PAGE_PARTS, PRICING_FEE_TEMPLATE_PANEL, PRICING_DECISION_CONTEXT, PRICING_PAGE_UTILS])
PRICING_API = (ROOT / "frontend/src/api/pricing.ts").read_text(encoding="utf-8")
CONTENT_MEDIA_STUDIO_MAIN = (ROOT / "frontend/src/features/content-planner/ContentMediaStudio.tsx").read_text(encoding="utf-8")
CONTENT_MEDIA_STUDIO_PARTS = (ROOT / "frontend/src/features/content-planner/ContentMediaStudioParts.tsx").read_text(encoding="utf-8")
CONTENT_MEDIA_STUDIO = "\n".join([CONTENT_MEDIA_STUDIO_MAIN, CONTENT_MEDIA_STUDIO_PARTS])
SELLER_IMAGE_EDITOR_WORKBENCH = (ROOT / "frontend/src/features/content-planner/SellerImageEditorWorkbench.tsx").read_text(encoding="utf-8")
SELLER_IMAGE_EDITOR_TYPES = (ROOT / "frontend/src/features/content-planner/SellerImageEditorTypes.ts").read_text(encoding="utf-8")
SELLER_IMAGE_EDITOR_WORKBENCH_CORE_PARTS = (ROOT / "frontend/src/features/content-planner/SellerImageEditorWorkbenchParts.tsx").read_text(encoding="utf-8")
SELLER_IMAGE_EDITOR_WORKBENCH_CANVAS_PARTS = (ROOT / "frontend/src/features/content-planner/SellerImageEditorWorkbenchCanvasParts.tsx").read_text(encoding="utf-8")
SELLER_IMAGE_EDITOR_WORKBENCH_PARTS = "\n".join([SELLER_IMAGE_EDITOR_WORKBENCH_CORE_PARTS, SELLER_IMAGE_EDITOR_WORKBENCH_CANVAS_PARTS])
SELLER_IMAGE_EDITOR_UTILS = (ROOT / "frontend/src/features/content-planner/SellerImageEditorUtils.ts").read_text(encoding="utf-8")
SELLER_IMAGE_SLOT_PLAN_PARSER = (ROOT / "frontend/src/features/content-planner/SellerImageSlotPlanParser.ts").read_text(encoding="utf-8")
SELLER_IMAGE_CROP_CONTROLS = (ROOT / "frontend/src/features/content-planner/SellerImageCropControls.tsx").read_text(encoding="utf-8")
SELLER_IMAGE_ENHANCEMENT_CONTROLS = (ROOT / "frontend/src/features/content-planner/SellerImageEnhancementControls.tsx").read_text(encoding="utf-8")
SELLER_IMAGE_EXPORT_TASK_SUMMARY = (ROOT / "frontend/src/features/content-planner/SellerImageExportTaskSummary.tsx").read_text(encoding="utf-8")
SELLER_IMAGE_OUTPUT_CONTROLS = (ROOT / "frontend/src/features/content-planner/SellerImageOutputControls.tsx").read_text(encoding="utf-8")
SELLER_IMAGE_WATERMARK_CONTROLS = (ROOT / "frontend/src/features/content-planner/SellerImageWatermarkControls.tsx").read_text(encoding="utf-8")
CONTENT_TITLE_GENERATOR = (ROOT / "frontend/src/features/content-planner/ContentTitleGenerator.tsx").read_text(encoding="utf-8")
SELLER_PLATFORM_LISTING_EDITOR = (ROOT / "frontend/src/features/content-planner/SellerPlatformListingEditorPanel.tsx").read_text(encoding="utf-8")
SELLER_PLATFORM_LISTING_EDITOR_PARTS = (ROOT / "frontend/src/features/content-planner/SellerPlatformListingEditorParts.tsx").read_text(encoding="utf-8")
LISTING_COPY_AI_ASSIST_PANEL_PATH = ROOT / "frontend/src/features/content-planner/ListingCopyAiAssistPanel.tsx"
LISTING_COPY_AI_ASSIST_PANEL = LISTING_COPY_AI_ASSIST_PANEL_PATH.read_text(encoding="utf-8") if LISTING_COPY_AI_ASSIST_PANEL_PATH.exists() else ""
LISTING_CRITICAL_ACTION_STRIP_PATH = ROOT / "frontend/src/features/content-planner/ListingCriticalActionStrip.tsx"
LISTING_CRITICAL_ACTION_STRIP = LISTING_CRITICAL_ACTION_STRIP_PATH.read_text(encoding="utf-8") if LISTING_CRITICAL_ACTION_STRIP_PATH.exists() else ""
SELLER_PLATFORM_LISTING_EDITOR_UTILS = (ROOT / "frontend/src/features/content-planner/SellerPlatformListingEditorUtils.ts").read_text(encoding="utf-8")
CONTENT_PLANNER_WORKSPACE = (ROOT / "frontend/src/features/content-planner/ContentPlannerWorkspace.tsx").read_text(encoding="utf-8")
LISTING_OBJECT_SCOPE_MAP = (ROOT / "frontend/src/features/content-planner/ListingObjectScopeMap.tsx").read_text(encoding="utf-8")
LISTING_STORE_OVERRIDE_EDITOR_PATH = ROOT / "frontend/src/features/content-planner/ListingStoreOverrideEditor.tsx"
LISTING_STORE_OVERRIDE_EDITOR = LISTING_STORE_OVERRIDE_EDITOR_PATH.read_text(encoding="utf-8") if LISTING_STORE_OVERRIDE_EDITOR_PATH.exists() else ""
LISTING_UNIFIED_EDITOR_SECTIONS = (ROOT / "frontend/src/features/content-planner/ListingUnifiedEditorSections.tsx").read_text(encoding="utf-8")
LISTING_SPECIFICATION_EDITOR_MAIN = (ROOT / "frontend/src/features/content-planner/ListingSpecificationEditor.tsx").read_text(encoding="utf-8")
LISTING_SPECIFICATION_EDITOR_PARTS = (ROOT / "frontend/src/features/content-planner/ListingSpecificationEditorParts.tsx").read_text(encoding="utf-8")
LISTING_SPECIFICATION_EDITOR_SKU_PARTS = (ROOT / "frontend/src/features/content-planner/ListingSpecificationEditorSkuParts.tsx").read_text(encoding="utf-8")
LISTING_SPECIFICATION_EDITOR = "\n".join([
    LISTING_SPECIFICATION_EDITOR_MAIN,
    LISTING_SPECIFICATION_EDITOR_PARTS,
    LISTING_SPECIFICATION_EDITOR_SKU_PARTS,
])
CONTENT_PUBLISH_GUIDE = (ROOT / "frontend/src/features/content-planner/ContentPublishGuide.tsx").read_text(encoding="utf-8")
CONTENT_PRODUCT_QUEUE_MAIN = (ROOT / "frontend/src/features/content-planner/ContentProductQueue.tsx").read_text(encoding="utf-8")
CONTENT_PRODUCT_QUEUE_PARTS = (ROOT / "frontend/src/features/content-planner/ContentProductQueueParts.tsx").read_text(encoding="utf-8")
CONTENT_PRODUCT_QUEUE_UTILS = (ROOT / "frontend/src/features/content-planner/ContentProductQueueUtils.ts").read_text(encoding="utf-8")
CONTENT_PRODUCT_QUEUE = "\n".join([CONTENT_PRODUCT_QUEUE_MAIN, CONTENT_PRODUCT_QUEUE_PARTS, CONTENT_PRODUCT_QUEUE_UTILS])
CONTENT_TASK_MATRIX = (ROOT / "frontend/src/features/content-planner/ContentTaskMatrix.tsx").read_text(encoding="utf-8")
LISTING_TEMPLATES_WORKSPACE = (ROOT / "frontend/src/features/listing-templates/ListingTemplatesWorkspace.tsx").read_text(encoding="utf-8")
BATCH_PUBLISH_PREVIEW = (ROOT / "frontend/src/features/batch-publish/BatchPublishPreviewStep.tsx").read_text(encoding="utf-8")
BATCH_PUBLISH_PREVIEW_PARTS = (ROOT / "frontend/src/features/batch-publish/BatchPublishPreviewParts.tsx").read_text(encoding="utf-8")
BATCH_PUBLISH_PREVIEW_SURFACE = "\n".join([BATCH_PUBLISH_PREVIEW, BATCH_PUBLISH_PREVIEW_PARTS])
BATCH_PUBLISH_SKU_READINESS = (ROOT / "frontend/src/features/batch-publish/BatchPublishSkuReadinessPanel.tsx").read_text(encoding="utf-8")
BATCH_PUBLISH_OVERRIDE_PREVIEW_PATH = ROOT / "frontend/src/features/batch-publish/StoreOverridePreviewPanel.tsx"
BATCH_PUBLISH_OVERRIDE_PREVIEW = BATCH_PUBLISH_OVERRIDE_PREVIEW_PATH.read_text(encoding="utf-8") if BATCH_PUBLISH_OVERRIDE_PREVIEW_PATH.exists() else ""
BATCH_PUBLISH_QUEUE = (ROOT / "frontend/src/features/batch-publish/ListingDraftQueue.tsx").read_text(encoding="utf-8")
BATCH_PUBLISH_COMPLETENESS = (ROOT / "frontend/src/features/batch-publish/ListingCompletenessPanel.tsx").read_text(encoding="utf-8")
BATCH_PUBLISH_RESULT = (ROOT / "frontend/src/features/batch-publish/BatchPublishResultStep.tsx").read_text(encoding="utf-8")
BATCH_PUBLISH_WORKSPACE = (ROOT / "frontend/src/features/batch-publish/BatchPublishWorkspace.tsx").read_text(encoding="utf-8")
BATCH_PUBLISH_SELECT = (ROOT / "frontend/src/features/batch-publish/BatchPublishSelectStep.tsx").read_text(encoding="utf-8")
BATCH_PUBLISH_SELECT_PARTS = (ROOT / "frontend/src/features/batch-publish/BatchPublishSelectParts.tsx").read_text(encoding="utf-8")
BATCH_PUBLISH_SELECT_UTILS = (ROOT / "frontend/src/features/batch-publish/BatchPublishSelectUtils.ts").read_text(encoding="utf-8")
BATCH_PUBLISH_SELECT_SURFACE = "\n".join([BATCH_PUBLISH_SELECT, BATCH_PUBLISH_SELECT_PARTS, BATCH_PUBLISH_SELECT_UTILS])
BATCH_PUBLISH_PREFLIGHT = (ROOT / "frontend/src/features/batch-publish/BatchPublishPreflightSummary.tsx").read_text(encoding="utf-8")
BATCH_PUBLISH_READINESS_CELLS = (ROOT / "frontend/src/features/batch-publish/BatchPublishReadinessCells.tsx").read_text(encoding="utf-8")
BATCH_PUBLISH_TARGET_VALIDATION = (ROOT / "frontend/src/features/batch-publish/BatchPublishTargetValidationPanel.tsx").read_text(encoding="utf-8")
PRODUCT_EDIT_PAGE = (ROOT / "frontend/src/pages/ProductEditPage.tsx").read_text(encoding="utf-8")
PRODUCT_DETAIL_TABS_MAIN = (ROOT / "frontend/src/features/products/ProductDetailTabs.tsx").read_text(encoding="utf-8")
PRODUCT_DETAIL_TABS_PARTS = (ROOT / "frontend/src/features/products/ProductDetailTabsParts.tsx").read_text(encoding="utf-8")
PRODUCT_DETAIL_TABS = "\n".join([PRODUCT_DETAIL_TABS_MAIN, PRODUCT_DETAIL_TABS_PARTS])
PRODUCT_LISTING_EDITOR_CHROME = (ROOT / "frontend/src/features/products/ProductListingEditorChrome.tsx").read_text(encoding="utf-8")
PRODUCT_LISTING_EDITOR_CONTENT = PRODUCT_DETAIL_TABS + PRODUCT_LISTING_EDITOR_CHROME
PRODUCT_IMAGES_PANEL = (ROOT / "frontend/src/features/products/ProductImagesPanel.tsx").read_text(encoding="utf-8")
PLATFORM_FIELD_GROUPS_MAIN = (ROOT / "frontend/src/components/shared/PlatformFieldGroups.tsx").read_text(encoding="utf-8")
PLATFORM_FIELD_GROUPS_PARTS = (ROOT / "frontend/src/components/shared/PlatformFieldGroupsParts.tsx").read_text(encoding="utf-8")
PLATFORM_FIELD_GROUPS = "\n".join([PLATFORM_FIELD_GROUPS_MAIN, PLATFORM_FIELD_GROUPS_PARTS])
PLATFORM_STORE_PRODUCTS_PANEL_PATH = ROOT / "frontend/src/features/products/PlatformStoreProductsPanel.tsx"
PLATFORM_STORE_PRODUCTS_PANEL = PLATFORM_STORE_PRODUCTS_PANEL_PATH.read_text(encoding="utf-8") if PLATFORM_STORE_PRODUCTS_PANEL_PATH.exists() else ""
PLATFORM_STORE_PRODUCTS_PANEL_PARTS = (ROOT / "frontend/src/features/products/PlatformStoreProductsPanelParts.tsx").read_text(encoding="utf-8")
PLATFORM_STORE_PRODUCT_UTILS = (ROOT / "frontend/src/features/products/PlatformStoreProductUtils.ts").read_text(encoding="utf-8")
PLATFORM_STORE_PRODUCTS_SURFACE = "\n".join([PLATFORM_STORE_PRODUCTS_PANEL, PLATFORM_STORE_PRODUCTS_PANEL_PARTS, PLATFORM_STORE_PRODUCT_UTILS])
PRODUCT_PLATFORM_ATTRIBUTES_PANEL = (ROOT / "frontend/src/features/products/ProductPlatformAttributesPanel.tsx").read_text(encoding="utf-8")
PRODUCT_LIST_PAGE = (ROOT / "frontend/src/pages/ProductListPage.tsx").read_text(encoding="utf-8")
PRODUCT_BULK_TOOLBAR = (ROOT / "frontend/src/features/products/ProductBulkToolbar.tsx").read_text(encoding="utf-8")
ORDER_LIST_PAGE = (ROOT / "frontend/src/pages/OrderListPage.tsx").read_text(encoding="utf-8")
ORDER_LIST_UTILS = (ROOT / "frontend/src/features/orders/OrderListUtils.ts").read_text(encoding="utf-8")
ORDER_FULFILLMENT_OVERVIEW = (ROOT / "frontend/src/features/orders/OrderFulfillmentOverview.tsx").read_text(encoding="utf-8")
ORDER_LIST_SURFACE = "\n".join([ORDER_LIST_PAGE, ORDER_LIST_UTILS, ORDER_FULFILLMENT_OVERVIEW])
ORDER_DETAIL_PAGE = (ROOT / "frontend/src/pages/OrderDetailPage.tsx").read_text(encoding="utf-8")
ORDER_DETAIL_PARTS = (ROOT / "frontend/src/features/orders/OrderDetailParts.tsx").read_text(encoding="utf-8")
ORDER_DETAIL_SURFACE = "\n".join([ORDER_DETAIL_PAGE, ORDER_DETAIL_PARTS])
SHIPMENT_LIST_PAGE = (ROOT / "frontend/src/pages/ShipmentListPage.tsx").read_text(encoding="utf-8")
SHIPMENT_DETAIL_PAGE = (ROOT / "frontend/src/pages/ShipmentDetailPage.tsx").read_text(encoding="utf-8")
AFTER_SALES_PAGE = (ROOT / "frontend/src/pages/AfterSalesPage.tsx").read_text(encoding="utf-8")
ORDER_SERVICE = (ROOT / "backend/app/services/order_service.py").read_text(encoding="utf-8")
ORDER_API = (ROOT / "backend/app/api/v1/orders.py").read_text(encoding="utf-8")
SHIPMENT_SERVICE = (ROOT / "backend/app/services/shipment_service.py").read_text(encoding="utf-8")
SYNC_SERVICE_BACKEND = (ROOT / "backend/app/services/sync_service.py").read_text(encoding="utf-8")
SYNC_BACKEND_API = (ROOT / "backend/app/api/v1/sync.py").read_text(encoding="utf-8")
ORDERS_API = (ROOT / "frontend/src/api/orders.ts").read_text(encoding="utf-8")
ORDER_TYPES = (ROOT / "frontend/src/types/order.ts").read_text(encoding="utf-8")
SHIPMENTS_API = (ROOT / "frontend/src/api/shipments.ts").read_text(encoding="utf-8")
USE_ORDERS_HOOK = (ROOT / "frontend/src/hooks/useOrders.ts").read_text(encoding="utf-8")
USE_SYNC_HOOK = (ROOT / "frontend/src/hooks/useSync.ts").read_text(encoding="utf-8")
USE_CONFIG_HOOK = (ROOT / "frontend/src/hooks/useConfig.ts").read_text(encoding="utf-8")
CONFIG_API = (ROOT / "frontend/src/api/config.ts").read_text(encoding="utf-8")
CONFIG_SERVICE = (ROOT / "backend/app/services/config_service.py").read_text(encoding="utf-8")
RISK_CONTROL_SERVICE = (ROOT / "backend/app/services/risk_control_service.py").read_text(encoding="utf-8")
RISK_CONTROL_SOURCE_SUMMARY_SERVICE = (ROOT / "backend/app/services/risk_control_source_summary_service.py").read_text(encoding="utf-8")
RISK_CONTROL_SALES_RISK_SERVICE = (ROOT / "backend/app/services/risk_control_sales_risk_service.py").read_text(encoding="utf-8")
FINANCE_PAGE = (ROOT / "frontend/src/pages/FinancePage.tsx").read_text(encoding="utf-8")
FINANCE_PAGE_UTILS = (ROOT / "frontend/src/features/finance/FinancePageUtils.ts").read_text(encoding="utf-8")
FINANCE_TREND_SNAPSHOT = (ROOT / "frontend/src/features/finance/FinanceTrendSnapshot.tsx").read_text(encoding="utf-8")
FINANCE_TRACEBACK_COLUMN = (ROOT / "frontend/src/features/finance/FinanceTracebackColumn.tsx").read_text(encoding="utf-8")
FINANCE_PAGE_SURFACE = "\n".join([FINANCE_PAGE, FINANCE_PAGE_UTILS, FINANCE_TREND_SNAPSHOT, FINANCE_TRACEBACK_COLUMN])
FINANCE_API = (ROOT / "frontend/src/api/finance.ts").read_text(encoding="utf-8")
FINANCE_LEDGER_PANEL = (ROOT / "frontend/src/features/finance/FinanceLedgerPanel.tsx").read_text(encoding="utf-8")
FINANCE_V5_SKU_FIELD_DICTIONARY = (ROOT / "frontend/src/features/finance/FinanceV5SkuFieldDictionary.tsx").read_text(encoding="utf-8")
FINANCE_SERVICE = (ROOT / "backend/app/services/finance_service.py").read_text(encoding="utf-8")
FINANCE_SCHEMA = (ROOT / "backend/app/schemas/finance.py").read_text(encoding="utf-8")
FINANCE_BACKEND_API = (ROOT / "backend/app/api/v1/finance.py").read_text(encoding="utf-8")
REPORT_SERVICE = (ROOT / "backend/app/services/report_service.py").read_text(encoding="utf-8")
REPORTS_WORKSPACE = (ROOT / "frontend/src/features/reports/ReportsWorkspace.tsx").read_text(encoding="utf-8")
REPORT_DISPLAY = (ROOT / "frontend/src/features/reports/ReportDisplay.tsx").read_text(encoding="utf-8")
REPORT_PANELS = (ROOT / "frontend/src/features/reports/ReportsPanels.tsx").read_text(encoding="utf-8")
REPORT_TYPES = (ROOT / "frontend/src/types/reports.ts").read_text(encoding="utf-8")
GROWTH_ENGINE_PAGE = (ROOT / "frontend/src/pages/GrowthEnginePage.tsx").read_text(encoding="utf-8")
PROMOTIONS_PAGE = (ROOT / "frontend/src/pages/PromotionsPage.tsx").read_text(encoding="utf-8")
AI_SUGGESTIONS_PAGE = (ROOT / "frontend/src/pages/AISuggestionsPage.tsx").read_text(encoding="utf-8")
OPERATIONS_WORKSPACE = (ROOT / "frontend/src/features/operations/OperationsWorkspace.tsx").read_text(encoding="utf-8")
COMPETITOR_MONITOR_PAGE = (ROOT / "frontend/src/pages/CompetitorMonitorPage.tsx").read_text(encoding="utf-8")
AUDIT_LOG_TAB = (ROOT / "frontend/src/pages/settings/AuditLogTab.tsx").read_text(encoding="utf-8")
INVENTORY_ALERT_WORKSPACE = (ROOT / "frontend/src/features/inventory-alerts/InventoryAlertWorkspace.tsx").read_text(encoding="utf-8")
INVENTORY_ALERT_PANELS_MAIN = (ROOT / "frontend/src/features/inventory-alerts/InventoryAlertPanels.tsx").read_text(encoding="utf-8")
INVENTORY_RISK_WORKBENCH_PARTS = (ROOT / "frontend/src/features/inventory-alerts/InventoryRiskWorkbenchParts.tsx").read_text(encoding="utf-8")
INVENTORY_ALERT_PANELS = "\n".join([INVENTORY_ALERT_PANELS_MAIN, INVENTORY_RISK_WORKBENCH_PARTS])
INVENTORY_ALERT_API = (ROOT / "frontend/src/api/inventoryAlerts.ts").read_text(encoding="utf-8")
INVENTORY_ALERT_HOOKS = (ROOT / "frontend/src/hooks/useInventoryAlerts.ts").read_text(encoding="utf-8")
SYNC_HOOKS = (ROOT / "frontend/src/hooks/useSync.ts").read_text(encoding="utf-8")
INVENTORY_ALERT_BACKEND_API = (ROOT / "backend/app/api/v1/inventory_alerts.py").read_text(encoding="utf-8")
INVENTORY_RISK_ACTION_SERVICE = (ROOT / "backend/app/services/inventory_risk_action_service.py").read_text(encoding="utf-8")
SETTINGS_BILLING_PANEL = (ROOT / "frontend/src/features/settings/SettingsBillingPanel.tsx").read_text(encoding="utf-8")
OPERATIONS_API = (ROOT / "frontend/src/api/operations.ts").read_text(encoding="utf-8")
PROMOTIONS_PAGE = (ROOT / "frontend/src/pages/PromotionsPage.tsx").read_text(encoding="utf-8")
PROMOTION_GOVERNANCE_PANEL = (ROOT / "frontend/src/features/promotions/PromotionGovernancePanel.tsx").read_text(encoding="utf-8")
PROMOTION_TYPE_RULE_GUIDE = (ROOT / "frontend/src/features/promotions/PromotionTypeRuleGuide.tsx").read_text(encoding="utf-8")
PROMOTION_PAGE_MODEL = (ROOT / "frontend/src/features/promotions/PromotionPageModel.ts").read_text(encoding="utf-8")
PROMOTION_PAGE_PARTS = (ROOT / "frontend/src/features/promotions/PromotionPageParts.tsx").read_text(encoding="utf-8")
PROMOTIONS_PAGE_SURFACE = "\n".join([PROMOTIONS_PAGE, PROMOTION_PAGE_MODEL, PROMOTION_PAGE_PARTS])
PROMOTION_WATERMARK_SELECTOR = (ROOT / "frontend/src/features/promotions/PromotionWatermarkSelector.tsx").read_text(encoding="utf-8")
PROMOTION_WATERMARK_UTILS = (ROOT / "frontend/src/features/promotions/PromotionWatermarkUtils.ts").read_text(encoding="utf-8")
PROMOTION_SYNC_UTILS = (ROOT / "frontend/src/features/promotions/PromotionSyncUtils.ts").read_text(encoding="utf-8")
PROMOTIONS_API = (ROOT / "frontend/src/api/promotions.ts").read_text(encoding="utf-8")
PROMOTIONS_BACKEND_API = (ROOT / "backend/app/api/v1/promotions.py").read_text(encoding="utf-8")
PROMOTION_SERVICE = (ROOT / "backend/app/services/promotion_service.py").read_text(encoding="utf-8")
PROMOTION_MODEL = (ROOT / "backend/app/models/promotion.py").read_text(encoding="utf-8")
PLATFORM_STATUS = (ROOT / "backend/app/integrations/status.py").read_text(encoding="utf-8")
PRODUCT_NORMALIZERS = (ROOT / "backend/app/integrations/product_normalizers.py").read_text(encoding="utf-8")
SHOPEE_CLIENT = (ROOT / "backend/app/integrations/shopee/client.py").read_text(encoding="utf-8")
TIKTOK_CLIENT = (ROOT / "backend/app/integrations/tiktok_shop/client.py").read_text(encoding="utf-8")
TEMU_CLIENT = (ROOT / "backend/app/integrations/temu/client.py").read_text(encoding="utf-8")
PRODUCT_SELLER_WORKBENCH = (ROOT / "frontend/src/features/products/ProductSellerWorkbench.tsx").read_text(encoding="utf-8")
PRODUCTS_API = (ROOT / "frontend/src/api/products.ts").read_text(encoding="utf-8")
SYNC_API = (ROOT / "frontend/src/api/sync.ts").read_text(encoding="utf-8")
LISTING_API = (ROOT / "frontend/src/api/listing.ts").read_text(encoding="utf-8")
BATCH_PUBLISH_SERVICE = (ROOT / "backend/app/services/batch_publish_service.py").read_text(encoding="utf-8")
LISTING_STORE_OVERRIDE_SERVICE = (ROOT / "backend/app/services/listing_store_override_service.py").read_text(encoding="utf-8")
PLATFORMS_API = (ROOT / "frontend/src/api/platforms.ts").read_text(encoding="utf-8")
PLATFORM_SETTINGS_PAGE = (ROOT / "frontend/src/pages/PlatformSettingsPage.tsx").read_text(encoding="utf-8")
PLATFORM_SETTINGS_CSS = (ROOT / "frontend/src/styles/platform-settings.css").read_text(encoding="utf-8")
PROFESSIONAL_WORKSPACE_FRAME_PATH = ROOT / "frontend/src/components/shared/ProfessionalWorkspaceFrame.tsx"
PROFESSIONAL_WORKSPACE_FRAME = PROFESSIONAL_WORKSPACE_FRAME_PATH.read_text(encoding="utf-8") if PROFESSIONAL_WORKSPACE_FRAME_PATH.exists() else ""
COMMAND_CENTER_FRAME_PATH = ROOT / "frontend/src/components/shared/CommandCenterFrame.tsx"
COMMAND_CENTER_FRAME = COMMAND_CENTER_FRAME_PATH.read_text(encoding="utf-8") if COMMAND_CENTER_FRAME_PATH.exists() else ""
BUSINESS_OBJECT_ACTION_BAR_PATH = ROOT / "frontend/src/components/shared/BusinessObjectActionBar.tsx"
BUSINESS_OBJECT_ACTION_BAR = BUSINESS_OBJECT_ACTION_BAR_PATH.read_text(encoding="utf-8") if BUSINESS_OBJECT_ACTION_BAR_PATH.exists() else ""
IMPLEMENTATION_PLAN = (ROOT / "docs/03_CBHunter_V5.0实施任务总表.md").read_text(encoding="utf-8")
UNIFIED_FIELD_DICTIONARY = (ROOT / "backend/app/data/default_unified_field_dictionary.json").read_text(encoding="utf-8")


def native_confirm_usages() -> list[str]:
    confirm_pattern = re.compile(r"(?<![A-Za-z0-9_$\.])confirm\s*\(|window\.confirm\s*\(")
    usages: list[str] = []
    for path in sorted(FRONTEND_SRC.rglob("*.ts")) + sorted(FRONTEND_SRC.rglob("*.tsx")):
        rel = path.relative_to(ROOT).as_posix()
        if rel in NATIVE_CONFIRM_ALLOWLIST:
            continue
        text = path.read_text(encoding="utf-8")
        for lineno, line in enumerate(text.splitlines(), start=1):
            if confirm_pattern.search(line):
                usages.append(f"{rel}:{lineno}")
    return usages
